---
# tasks file for node_exporter
- name: Criando usuario node_exporter
  become: yes
  become_method: sudo  
  user:
    name: node_exporter
    create_home: no
    shell: /bin/false

- name: Realizando Download do node_exporter
  get_url:
    dest: /home/ubuntu/
    mode: "644"
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz"