- name: Security Group
  local_action: 
    module: ec2_group
    name: "{{ security_group }}"
    description: Sg with ansible
    region: "{{ region }}"
    rules:
     - proto: tcp
       from_port: 22
       to_port: 22
       cidr_ip: 0.0.0.0/0
    rules_egress:
     - proto: all
       cidr_ip: 0.0.0.0/0
  register: fw

- name: Instancia EC2
  local_action: ec2
    group={{ security_group }}
    instance_type={{ instance_type }}
    image={{ image }}
    wait=true
    region={{ region }}
    keypair={{ keypair }}
    count={{ count }}
  register: ec2

- name: Inventario Temp
  add_host: name={{ item.public_ip }} groups=my-group
  with_items: "{{ ec2.instances }}"

- name: Public IP da instancia no arquivo hosts
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter="[aws_instances]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: Esperando SSH
  local_action: wait_for
    host={{ item.public_ip }}
    port=22
    state=started
  with_items: "{{ ec2.instances }}"

- name: Tag na instancia
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ec2.instances}}"
  args:
    tags:
      Name: Blackbeard
