--- 

- rpm_key:
    state: present
    key: http://repo.zabbix.com/zabbix-official-repo.key
  when: "ansible_distribution == \"CentOS\""

- name: "Install the Zabbix repository for CentOS 6"
  yum: 
    name: http://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm
    state: present
  when: "ansible_distribution == \"CentOS\" and ansible_distribution_major_version == \"6\""

- name: "Install the Zabbix repository for CentOS 7"
  yum: 
    name: http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    state: present
  when: "ansible_distribution == \"CentOS\" and ansible_distribution_major_version == \"7\""

- name: "Install the Zabbix repository for CentOS 8"
  yum: 
    name: http://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-2.el8.noarch.rpm
    state: present
  when: "ansible_distribution == \"CentOS\" and ansible_distribution_major_version == \"8\""

- name: "Installation Zabbix Agent "
  yum: 
    name: zabbix-agent
    state: present
  when: "ansible_distribution == \"CentOS\""
  notify:
    - Start zabbix-agent

- name: "Configuring Server in zabbix_agentd.conf"
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="^Server=127.0.0.1" line="Server=192.168.0.2" state=present
  notify: Restart zabbix-agent

- name: "Configuring ServerActive in zabbix_agentd.conf"
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="^ServerActive=127.0.0.1" line="ServerActive=192.168.0.2" state=present
  notify: Restart zabbix-agent

- name: "Configuring StartAgents in zabbix_agentd.conf"
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="^# StartAgents=3" line="# StartAgents=5" state=present
  notify: Restart zabbix-agent
  
  
